version: 0.0.0.{build}

clone_depth: 1

image: macOS-Monterey

before_build:
  - 'git submodule update --init --recursive'

build_script:
  - sh: set -o pipefail && xcodebuild -project Moonlight.xcodeproj -scheme "Moonlight" -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Pro" clean build | xcpretty
  - sh: set -o pipefail && xcodebuild -project Moonlight.xcodeproj -scheme "Moonlight" -destination "platform=iOS Simulator,OS=16.1,name=iPad (10th generation)" clean build | xcpretty
  - sh: set -o pipefail && xcodebuild -project Moonlight.xcodeproj -scheme "Moonlight TV" -destination "platform=tvOS Simulator,OS=16.1,name=Apple TV 4K (3rd generation)" clean build | xcpretty

deploy: off
